name: Builds
on:
  workflow_call:
    inputs:
      filter:
        required: true
        type: string

jobs:
  matrix:
    name: Build outputs matrix (${{ inputs.filter }})
    runs-on: ubuntu-24.04
    outputs:
      matrix: ${{ steps.build-matrix.outputs.matrix }}
    steps:
      - uses: samueldr/nix-build-action@latest
        with:
          expression-file: .ci/build-matrices.nix
          nix-build-extra-arguments: --argstr filter ${{ inputs.filter }}
      - id: build-matrix
        name: "Generate Build Matrix"
        run: |
          printf "matrix=%s\n" "$(cat result)" >> "$GITHUB_OUTPUT"

  builds:
    name: ${{ matrix.attr }}
    needs: matrix
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.matrix.outputs.matrix) }}
    steps:
      - uses: samueldr/nix-build-action@latest
        with:
          initial-random-delay-max: 180 # 3 minutes
          space-making-action: "more-space-action"
          attributes: ${{ matrix.attr }}
